[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
primaryColor = "#1E88E5"
backgroundColor = "#F8F9FA"
secondaryBackgroundColor = "#ffffff"
textColor = "#212121"
font = "sans serif"

# Dark mode colors
[theme.dark]
primaryColor = "#1E88E5"
backgroundColor = "#1A1A1A"
secondaryBackgroundColor = "#2D2D2D"
textColor = "#FFFFFF"